#配置ConfigurationProperties测试
custom:
  username: richard.guo
  password: 2wsxVFR_
  books:
    - name: how to study
      author: jack
      price: 20.0
    - name: run quickly
      author: mike
      price: 18.8
  bookIndex:
    20170917:
      name: how to study
      author: jack
      price: 20.0
    20170918:
      name: run quickly
      author: mike
      price: 18.8